name: '1 - events' 

on: 
    push:
        branches:
            - "feature/**"

jobs:
    build:
        runs-on: "primeiro-teste-linux-dev"
        steps:
            - run: echo '---- ❤️primeiro teste'
              shell: bash